services:
  - type: web
    name: benkthomp
    runtime: python
    buildCommand: pip install .
    startCommand: gunicorn "benkthomp.app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: SECRET_KEY
        generateValue: true
